const foods = [
    {
        id: 0,
        name: "chicken",
        kcal: 700,
        description: "Chicken legs with lettuce",
        imgSrc: "foodImages/chicken.png",
       
      },
      {
        id: 1,
        name: "chips",
        kcal: 600,
        description: "Chips Lays wavy",
        imgSrc: "foodImages/chips.png",
      },
      {
        id: 2,
        name: "fish",
        kcal: 450,
        description: " Fish with rice, fried potatoes and salad",
        imgSrc: "foodImages/fish.png",
      },
      {
        id: 3,
        name: "friedEgg",
        kcal: 450,
        description: " Fried Eggs",
        imgSrc: "foodImages/friedEgg.png",
      },
      {
        id: 4,
        name: "Fruits",
        kcal: 200,
        description: " Different types of fruits",
        imgSrc: "foodImages/Fruits.png",
      },
      {
        id: 5,
        name: "iceCream",
        kcal: 500,
        description: "Ice cream with 3 different flavours",
        imgSrc: "foodImages/iceCream.png",
      },
      {
        id: 6,
        name: "meatballs",
        kcal: 550,
        description:"Meatballs with dill",
        imgSrc: "foodImages/meatballs.png",
      },
      {
        id: 7,
        name: "oatmeal",
        kcal: 650,
        description:"Oatmeal with hazelnuts, peanut butter, macadamia, raisins and banana",
        imgSrc: "foodImages/oatmeal.png",
      },
      {
        id: 8,
        name: "sandwich",
        kcal: 400,
        description: " Sandwich with ham, lettuce, tomatoes and cheese",
        imgSrc: "foodImages/sandwich.png",
      },
      {
        id: 9,
        name: "spaghetti",
        kcal: 700,
        description: "Spaghetti bolognese",
        imgSrc: "foodImages/spaghetti.png",
      },
      {
        id: 10,
        name: "steak",
        kcal: 500,
        description: "Meduim-rare steak",
        imgSrc: "foodImages/steak.png",
      },
      {
        id: 11,
        name: "stirFry",
        kcal: 550,
        description: "Stir fry with beef, rice, green beans, broccoli and peppers",
        imgSrc: "foodImages/stirFry.png",
      },
    
    ];